version: '3.8'
services:
  eureka:
    container_name: eureka
    network_mode: host
    healthcheck:
      test: curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 25s
    build:
      context: .
      args:
        APP_NAME: eureka
    restart: always
    volumes:
      - ./.gradle:/root/.gradle

  balancer:
    container_name: balancer
    network_mode: host
    healthcheck:
      test: curl --fail --silent localhost:4433/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      eureka:
        condition: service_healthy
      config:
        condition: service_healthy
    build:
      context: .
      args:
        APP_NAME: balancer
    restart: always
    volumes:
      - ./.gradle:/root/.gradle

  config:
    container_name: config
    network_mode: host
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 25s
    build:
      context: .
      args:
        APP_NAME: config
    restart: always
    volumes:
      - ./.gradle:/root/.gradle
   
  auth:
    container_name: auth
    network_mode: host
    depends_on:
      balancer:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 25s
    build:
      context: .
      args:
        APP_NAME: auth
    restart: always
    volumes:
      - ./.gradle:/root/.gradle

  content:
    container_name: content
    network_mode: host
    depends_on:
      balancer:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 25s
    build:
      context: .
      args:
        APP_NAME: content
    restart: always
    volumes:
      - ./.gradle:/root/.gradle

  email:
    container_name: email
    network_mode: host
    depends_on:
      balancer:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 25s
    build:
      context: .
      args:
        APP_NAME: email
    restart: always
    volumes:
      - ./.gradle:/root/.gradle
