server:
  port: 8083
  address: 0.0.0.0

eureka:
  client.serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
  instance.prefer-ip-address: true

spring:
  application:
    name: email

  config.import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
      fail-fast: false
      username: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

  mail:
    emulator: false #disable spam
    host: 'smtp.gmail.com'
    port: 587
    #username: 'test@gmail.com'
    #password: 'pass'
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

logging:
  pattern:
    console: "%blue(%d) %highlight(%-5level) %green(%t) %yellow(%c{1.}): %msg%n"
    file: "%d %-5level %t %c{1.}: %msg%n"
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    root: INFO
